name: train
 
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  run:
    environment: aws
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
 
      - uses: iterative/setup-cml@v1
 
      - uses: iterative/setup-dvc@v1
 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 3600
 
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVC_EXP_AUTO_PUSH: 1
          DVC_EXP_GIT_REMOTE: origin
          DVCLIVE_LOG_LEVEL: DEBUG
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          STUDIO_REPO_URL: github:iterative/lstm_seq2seq
        run: |
          cml ci
          pip install --upgrade -r requirements.txt

          dvc pull --allow-missing
          dvc exp run -S model=full -n pmrowla-test
          dvc exp push -v --rev HEAD origin

          git push origin `git show-ref pmrowla-test | awk '{print $2}`:`git show-ref pmrowla-test | awk '{print $2}`
